plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
  - key: tags.Environment
    prefix: tag_Environment_
  - key: tags.Role
    prefix: tag_Role_
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
