---
- name: Configure web server
  hosts: all
  become: true
  tasks:
    - name: Install Nginx (cross-platform)
      package:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true
